(function () {
  "use strict";

  window.__BRAND__ = {
    name: "Kronos Paper",
    legal: "Kronos Paper S.A.",
    year: new Date().getFullYear(),

    nav: [
      { href: "#aplicaciones", label: { es: "Aplicaciones", en: "Applications" } },
      { href: "#catalogo", label: { es: "Catálogo", en: "Catalog" } },
      { href: "#especificaciones", label: { es: "Especificaciones", en: "Specs" } },
      { href: "#calidad", label: { es: "Calidad", en: "Quality" } },
      { href: "#contacto", label: { es: "Contacto", en: "Contact" } },
    ],

    stats: [
      { value: 340, suffix: "", label: { es: "toneladas de papel al mes", en: "tons of paper per month" } },
      { value: 1200, suffix: "+", label: { es: "comercios abastecidos", en: "stores supplied" } },
      { value: 8, suffix: "", label: { es: "líneas de rollo en catálogo", en: "roll lines in catalog" } },
      { value: 24, suffix: "h", label: { es: "despacho desde bodega", en: "warehouse dispatch" } },
    ],

    products: [
      { id: "kp-8080f", line: "Térmico Fiscal 80×80", app: "pos", width: "80 mm", diam: "80 mm", core: "12 / 25.4 mm", gsm: "55 g/m²", length: "≈ 60 m",
        use: { es: "Impresoras fiscales, cajas registradoras, supermercados", en: "Fiscal printers, cash registers, supermarkets" } },
      { id: "kp-5760t", line: "Térmico TPV 57×60", app: "pos", width: "57 mm", diam: "60 mm", core: "12 mm", gsm: "48 g/m²", length: "≈ 45 m",
        use: { es: "TPV de restauración, farmacias, retail", en: "Restaurant POS, pharmacies, retail" } },
      { id: "kp-5740f", line: "Térmico Fiscal 57×40", app: "pos", width: "57 mm", diam: "40 mm", core: "12 mm", gsm: "48 g/m²", length: "≈ 25 m",
        use: { es: "Impresoras fiscales compactas, kioscos", en: "Compact fiscal printers, kiosks" } },
      { id: "kp-5740d", line: "Datáfono 57×40 núcleo 8", app: "datafono", width: "57 mm", diam: "40 mm", core: "8 mm", gsm: "44 g/m²", length: "≈ 18 m",
        use: { es: "Terminales de pago inalámbricos", en: "Wireless payment terminals" } },
      { id: "kp-5725d", line: "Datáfono 57×25 mini", app: "datafono", width: "57 mm", diam: "25 mm", core: "8 mm", gsm: "44 g/m²", length: "≈ 8 m",
        use: { es: "Terminales portátiles de bajo volumen", en: "Low-volume portable terminals" } },
      { id: "kp-216fax", line: "Fax térmico 216×30", app: "oficina", width: "216 mm", diam: "90 mm", core: "12 mm", gsm: "60 g/m²", length: "30 m",
        use: { es: "Fax de oficina, equipos multifunción", en: "Office fax, multifunction devices" } },
      { id: "kp-57bond", line: "Calculadora bond 57", app: "oficina", width: "57 mm", diam: "60 mm", core: "11.5 mm", gsm: "52 g/m²", length: "≈ 20 m",
        use: { es: "Sumadoras y calculadoras impresoras", en: "Adding machines and printing calculators" } },
      { id: "kp-58bas", line: "Báscula térmica 58×40", app: "oficina", width: "58 mm", diam: "40 mm", core: "12 mm", gsm: "50 g/m²", length: "≈ 22 m",
        use: { es: "Básculas comerciales con impresión de peso", en: "Commercial scales with weight printing" } },
    ],

    quality: [
      { title: { es: "Libre de BPA y BPS", en: "BPA & BPS free" },
        body: { es: "Recubrimiento térmico certificado sin bisfenol, seguro para manipulación diaria en comercio y alimentación.", en: "Certified bisphenol-free thermal coating, safe for daily handling in retail and food service." } },
      { title: { es: "Producción trazable", en: "Traceable production" },
        body: { es: "Cada bobina madre queda registrada por lote — de la planta al rollo que llega a tu caja.", en: "Every parent reel is logged by batch — from the plant to the roll that reaches your register." } },
      { title: { es: "Papel de origen responsable", en: "Responsibly sourced paper" },
        body: { es: "Fibra proveniente de proveedores con cadena de custodia certificada y programas de reforestación.", en: "Fiber from suppliers with certified chain of custody and reforestation programs." } },
    ],

    testimonials: [
      { quote: { es: "Cambiamos a Kronos hace dos años y dejamos de tener cortes de impresión a mitad de ticket. El rollo rinde lo que dice la ficha.", en: "We switched to Kronos two years ago and stopped getting print cutouts mid-receipt. The roll delivers exactly what the spec sheet promises." },
        author: { es: "Gerencia de operaciones", en: "Operations management" }, role: { es: "Cadena de supermercados regional", en: "Regional supermarket chain" } },
      { quote: { es: "El diámetro reducido para datáfono nos resolvió un problema real: los terminales inalámbricos ya no se traban al cerrar la tapa.", en: "The smaller diameter for card terminals solved a real problem: wireless units no longer jam when the lid closes." },
        author: { es: "Jefatura de sistemas de pago", en: "Payment systems lead" }, role: { es: "Procesador de pagos", en: "Payment processor" } },
      { quote: { es: "Un solo proveedor para fiscal, datáfono y báscula simplificó la compra. Antes coordinábamos con tres.", en: "One supplier for fiscal, card terminal and scale rolls simplified purchasing. We used to coordinate with three." },
        author: { es: "Compras corporativas", en: "Corporate purchasing" }, role: { es: "Franquicia de comida rápida", en: "Fast food franchise" } },
    ],

    coverage: [
      { value: 24, suffix: "–48h", label: { es: "entrega en zona metropolitana", en: "delivery in metro area" } },
      { value: 15, suffix: "", label: { es: "años operando líneas fiscales", en: "years running fiscal lines" } },
      { value: 50, suffix: "+", label: { es: "unidades, pedido mínimo", en: "units, minimum order" } },
    ],

    contact: {
      email: "kronospaper@gmail.com",
      whatsappDisplay: "+58 414-265-6739",
      whatsappHref: "https://wa.me/584142656739",
      tiktokHref: "https://www.tiktok.com/@kronospaper",
      youtubeHref: "https://www.youtube.com/@kronospaper",
      address: { es: "Parque Industrial Norte, Nave 12", en: "North Industrial Park, Warehouse 12" },
    },
  };

  window.__I18N__ = {
    es: {
      html_lang: "es",
      meta_title: "Kronos Paper — Papel térmico y bond de precisión para punto de venta",
      meta_desc: "Rollos térmicos y bond calibrados para impresoras fiscales, datáfonos, fax, calculadoras y básculas. Fabricación trazable, libre de BPA, entrega en 24–48h.",

      nav_quote_btn: "Solicitar cotización",
      nav_open_menu: "Abrir menú",
      nav_cart_label: "Ver carrito",
      nav_aplicaciones: "Aplicaciones",
      nav_catalogo: "Catálogo",
      nav_especificaciones: "Especificaciones",
      nav_calidad: "Calidad",
      nav_contacto: "Contacto",
      lang_es: "ES",
      lang_en: "EN",

      hero_meta: "Fábrica activa · Despacho hoy",
      hero_glyph: "Ø25–90mm · 44–60 g/m² · Sin BPA",
      hero_title_html: "El papel que tu negocio <em>no nota</em> — hasta que falta.",
      hero_sub: "Rollos térmicos y bond calibrados milímetro a milímetro para la máquina exacta donde van a vivir: impresora fiscal, datáfono, fax, calculadora o báscula.",
      btn_quote: "Solicitar cotización",
      btn_specs: "Ver especificaciones",

      manifesto_p1_html: "No fabricamos “papel para impresora”. Fabricamos el <em>rollo exacto</em> que necesita cada motor de impresión: el núcleo correcto para que no se atasque, el diámetro correcto para que quepa en la tapa, el gramaje correcto para que la imagen térmica no se desvanezca en tres días.",
      manifesto_p2: "Cada línea de producto nace de desarmar la máquina donde va a usarse — no de una hoja de especificaciones genérica.",

      apps_kicker: "Aplicaciones reales",
      apps_title_html: "Cada rollo, calibrado para <em>su máquina</em>.",
      apps_sub: "Así se ve el papel de Kronos funcionando donde realmente trabaja.",

      app_pos_kicker: "01 · Punto de venta",
      app_pos_title: "Impresoras fiscales y TPV",
      app_pos_summary: "El rollo que soporta el ritmo de una caja: corte limpio, imagen térmica estable y compatibilidad certificada con los motores de impresión más usados en retail.",
      app_pos_caption_eyebrow: "Cómo funciona",
      app_pos_caption: "El rollo gira, alimenta el cabezal térmico y corta el ticket al cerrar la venta.",
      app_pos_k_ancho: "Ancho", app_pos_v_ancho: "57 / 80 mm",
      app_pos_k_nucleo: "Núcleo", app_pos_v_nucleo: "12 · 25.4 mm",
      app_pos_k_diam: "Diámetro externo", app_pos_v_diam: "40 – 80 mm",
      app_pos_k_gramaje: "Gramaje", app_pos_v_gramaje: "48 – 55 g/m²",
      app_pos_k_compat: "Compatibilidad", app_pos_v_compat: "Epson TM-T88, Bixolon, Star, Hasar",

      app_datafono_kicker: "02 · Pago con tarjeta",
      app_datafono_title: "Datáfonos y terminales de pago",
      app_datafono_summary: "Núcleo reducido y diámetro compacto para terminales inalámbricos: menos peso en el bolsillo del vendedor, misma nitidez en el comprobante.",
      app_datafono_caption_eyebrow: "Cómo funciona",
      app_datafono_caption: "El terminal lee la tarjeta y el rollo compacto imprime el comprobante al instante.",
      app_datafono_k_ancho: "Ancho", app_datafono_v_ancho: "57 mm",
      app_datafono_k_nucleo: "Núcleo", app_datafono_v_nucleo: "8 mm",
      app_datafono_k_diam: "Diámetro externo", app_datafono_v_diam: "25 – 40 mm",
      app_datafono_k_gramaje: "Gramaje", app_datafono_v_gramaje: "44 g/m²",
      app_datafono_k_compat: "Compatibilidad", app_datafono_v_compat: "Ingenico Move, PAX A920, Verifone e355",

      app_oficina_kicker: "03 · Equipos de oficina",
      app_oficina_title: "Fax, calculadoras y básculas",
      app_oficina_summary: "Tres máquinas, tres formatos de rollo distintos: papel térmico ancho para fax, bond bicapa para sumadoras y ticket calibrado para el peso exacto en báscula.",
      app_oficina_k_fax: "Fax", app_oficina_v_fax: "216 mm · núcleo 12 mm",
      app_oficina_k_calc: "Calculadora", app_oficina_v_calc: "57 mm bond · núcleo 11.5 mm",
      app_oficina_k_bas: "Báscula", app_oficina_v_bas: "58 mm térmico · núcleo 12 mm",
      app_oficina_k_compat: "Compatibilidad", app_oficina_v_compat: "Panasonic, Casio, Toledo, CAS, Dibal",

      office_fax_title: "Fax térmico", office_fax_dim: "216×30mm",
      office_fax_desc: "Recibe documentos por línea telefónica y los imprime al llegar.",
      office_calc_title: "Calculadora bond", office_calc_dim: "57mm",
      office_calc_desc: "Imprime cada operación en la cinta para dejar registro de la suma.",
      office_bas_title: "Báscula térmica", office_bas_dim: "58×40mm",
      office_bas_desc: "Pesa el producto e imprime el ticket con el precio exacto.",

      video_demo_badge: "Demo",
      video_pause: "Pausar demo",
      video_play: "Reproducir demo",

      showcase_kicker: "Catálogo",
      showcase_title_html: "Ocho líneas de rollo, <em>un solo proveedor</em>.",
      showcase_sub: "Desliza para ver el formato exacto que necesita tu equipo.",
      showcase_hint: "Desliza o haz scroll",
      add_to_cart: "Agregar",
      added_to_cart: "Agregado",

      specs_kicker: "Ficha técnica",
      specs_title_html: "Especificaciones <em>comparadas</em>.",
      specs_sub: "Los mismos datos que verías en nuestra hoja de producto, en una sola tabla.",
      specs_th_line: "Línea", specs_th_app: "Aplicación", specs_th_width: "Ancho", specs_th_diam: "Diámetro ext.",
      specs_th_core: "Núcleo", specs_th_gsm: "Gramaje", specs_th_length: "Longitud",
      specs_app_pos: "POS / Fiscal", specs_app_datafono: "Datáfono", specs_app_oficina: "Oficina",

      quality_kicker: "Calidad",
      quality_title_html: "No es solo papel, es <em>consistencia</em>.",
      quality_sub: "Tres compromisos que sostenemos en cada bobina que sale de planta.",

      testi_kicker: "Clientes",
      testi_title_html: "Lo que dicen quienes <em>ya no piensan en el papel</em>.",

      cta_kicker: "Cotización",
      cta_title_html: "Cuéntanos qué máquina <em>alimenta</em>.",
      cta_sub: "Dinos el equipo, el volumen mensual y te devolvemos una cotización con el formato exacto de rollo — no una lista genérica.",

      form_name: "Nombre", form_name_ph: "Tu nombre",
      form_company: "Empresa", form_company_ph: "Nombre de tu negocio",
      form_email: "Correo", form_email_ph: "tu@empresa.com",
      form_machine: "Tipo de equipo", form_machine_select: "Selecciona…",
      form_opt_fiscal: "Impresora fiscal / TPV", form_opt_datafono: "Datáfono / terminal de pago",
      form_opt_fax: "Fax", form_opt_calc: "Calculadora / sumadora", form_opt_bas: "Báscula", form_opt_other: "Otro",
      form_msg: "Volumen mensual y detalles", form_msg_ph: "Ej: 40 cajas, rollo 80×80, entrega quincenal",
      form_note: "Respondemos en menos de un día hábil con precio y disponibilidad.",
      form_sending: "Enviando…",
      form_success_title: "Solicitud recibida",
      form_success_body: "Un asesor de Kronos Paper revisará tu equipo y te escribirá con la ficha exacta de rollo.",
      form_close: "Cerrar",

      cart_title: "Tu carrito de cotización",
      cart_close: "Cerrar carrito",
      cart_empty: "Aún no agregaste rollos. Explora el catálogo y agrega los que necesites.",
      cart_items_count: "artículos",
      cart_go_quote: "Solicitar cotización de este pedido",
      cart_remove: "Quitar",

      footer_tagline: "Papel térmico y bond de precisión para el ecosistema de punto de venta.",
      footer_nav_h: "Navegación",
      footer_company_h: "Empresa",
      footer_contact_h: "Contacto",
      footer_rights: "Todos los derechos reservados.",
      footer_built: "Sitio construido con GSAP + CSS — sin frameworks.",

      social_whatsapp: "Escríbenos por WhatsApp",
      social_email: "Escríbenos por correo",
      social_tiktok: "Síguenos en TikTok",
      social_youtube: "Síguenos en YouTube",
    },

    en: {
      html_lang: "en",
      meta_title: "Kronos Paper — Precision thermal & bond paper for point of sale",
      meta_desc: "Thermal and bond rolls calibrated for fiscal printers, card terminals, fax, calculators and scales. Traceable manufacturing, BPA-free, 24–48h delivery.",

      nav_quote_btn: "Request a quote",
      nav_open_menu: "Open menu",
      nav_cart_label: "View cart",
      nav_aplicaciones: "Applications",
      nav_catalogo: "Catalog",
      nav_especificaciones: "Specs",
      nav_calidad: "Quality",
      nav_contacto: "Contact",
      lang_es: "ES",
      lang_en: "EN",

      hero_meta: "Factory active · Shipping today",
      hero_glyph: "Ø25–90mm · 44–60 g/m² · BPA-free",
      hero_title_html: "The paper your business <em>doesn't notice</em> — until it runs out.",
      hero_sub: "Thermal and bond rolls calibrated to the millimeter for the exact machine they'll live in: fiscal printer, card terminal, fax, calculator or scale.",
      btn_quote: "Request a quote",
      btn_specs: "View specifications",

      manifesto_p1_html: "We don't make “printer paper.” We make the <em>exact roll</em> every print engine needs: the right core so it never jams, the right diameter so it fits the lid, the right weight so the thermal image doesn't fade in three days.",
      manifesto_p2: "Every product line starts by taking apart the machine it will run in — not from a generic spec sheet.",

      apps_kicker: "Real-world applications",
      apps_title_html: "Every roll, calibrated for <em>its machine</em>.",
      apps_sub: "This is Kronos paper running where it actually works.",

      app_pos_kicker: "01 · Point of sale",
      app_pos_title: "Fiscal printers & POS",
      app_pos_summary: "The roll that keeps up with a register's pace: clean cut, stable thermal image and certified compatibility with the print engines retail uses most.",
      app_pos_caption_eyebrow: "How it works",
      app_pos_caption: "The roll spins, feeds the thermal head, and cuts the ticket the moment the sale closes.",
      app_pos_k_ancho: "Width", app_pos_v_ancho: "57 / 80 mm",
      app_pos_k_nucleo: "Core", app_pos_v_nucleo: "12 · 25.4 mm",
      app_pos_k_diam: "Outer diameter", app_pos_v_diam: "40 – 80 mm",
      app_pos_k_gramaje: "Weight", app_pos_v_gramaje: "48 – 55 g/m²",
      app_pos_k_compat: "Compatibility", app_pos_v_compat: "Epson TM-T88, Bixolon, Star, Hasar",

      app_datafono_kicker: "02 · Card payment",
      app_datafono_title: "Card terminals",
      app_datafono_summary: "Smaller core and compact diameter for wireless terminals: less weight in the seller's pocket, the same sharp receipt.",
      app_datafono_caption_eyebrow: "How it works",
      app_datafono_caption: "The terminal reads the card and the compact roll prints the receipt instantly.",
      app_datafono_k_ancho: "Width", app_datafono_v_ancho: "57 mm",
      app_datafono_k_nucleo: "Core", app_datafono_v_nucleo: "8 mm",
      app_datafono_k_diam: "Outer diameter", app_datafono_v_diam: "25 – 40 mm",
      app_datafono_k_gramaje: "Weight", app_datafono_v_gramaje: "44 g/m²",
      app_datafono_k_compat: "Compatibility", app_datafono_v_compat: "Ingenico Move, PAX A920, Verifone e355",

      app_oficina_kicker: "03 · Office equipment",
      app_oficina_title: "Fax, calculators & scales",
      app_oficina_summary: "Three machines, three different roll formats: wide thermal paper for fax, two-ply bond for adding machines, and a ticket calibrated to the exact weight on a scale.",
      app_oficina_k_fax: "Fax", app_oficina_v_fax: "216 mm · 12 mm core",
      app_oficina_k_calc: "Calculator", app_oficina_v_calc: "57 mm bond · 11.5 mm core",
      app_oficina_k_bas: "Scale", app_oficina_v_bas: "58 mm thermal · 12 mm core",
      app_oficina_k_compat: "Compatibility", app_oficina_v_compat: "Panasonic, Casio, Toledo, CAS, Dibal",

      office_fax_title: "Thermal fax", office_fax_dim: "216×30mm",
      office_fax_desc: "Receives documents over the phone line and prints them as they arrive.",
      office_calc_title: "Bond calculator", office_calc_dim: "57mm",
      office_calc_desc: "Prints every operation on the tape to keep a record of the sum.",
      office_bas_title: "Thermal scale", office_bas_dim: "58×40mm",
      office_bas_desc: "Weighs the product and prints the ticket with the exact price.",

      video_demo_badge: "Demo",
      video_pause: "Pause demo",
      video_play: "Play demo",

      showcase_kicker: "Catalog",
      showcase_title_html: "Eight roll lines, <em>one supplier</em>.",
      showcase_sub: "Slide to find the exact format your equipment needs.",
      showcase_hint: "Slide or scroll",
      add_to_cart: "Add",
      added_to_cart: "Added",

      specs_kicker: "Spec sheet",
      specs_title_html: "Specifications <em>compared</em>.",
      specs_sub: "The same data you'd see on our product sheet, in one table.",
      specs_th_line: "Line", specs_th_app: "Application", specs_th_width: "Width", specs_th_diam: "Outer diam.",
      specs_th_core: "Core", specs_th_gsm: "Weight", specs_th_length: "Length",
      specs_app_pos: "POS / Fiscal", specs_app_datafono: "Card terminal", specs_app_oficina: "Office",

      quality_kicker: "Quality",
      quality_title_html: "It's not just paper, it's <em>consistency</em>.",
      quality_sub: "Three commitments we hold on every reel that leaves the plant.",

      testi_kicker: "Clients",
      testi_title_html: "What people who <em>no longer think about paper</em> say.",

      cta_kicker: "Quote",
      cta_title_html: "Tell us which machine <em>you're feeding</em>.",
      cta_sub: "Tell us the equipment and the monthly volume, and we'll send back a quote for the exact roll format — not a generic list.",

      form_name: "Name", form_name_ph: "Your name",
      form_company: "Company", form_company_ph: "Your business name",
      form_email: "Email", form_email_ph: "you@company.com",
      form_machine: "Equipment type", form_machine_select: "Select…",
      form_opt_fiscal: "Fiscal printer / POS", form_opt_datafono: "Card terminal",
      form_opt_fax: "Fax", form_opt_calc: "Calculator / adding machine", form_opt_bas: "Scale", form_opt_other: "Other",
      form_msg: "Monthly volume and details", form_msg_ph: "E.g.: 40 registers, 80×80 roll, biweekly delivery",
      form_note: "We reply within one business day with price and availability.",
      form_sending: "Sending…",
      form_success_title: "Request received",
      form_success_body: "A Kronos Paper advisor will review your equipment and get back to you with the exact roll spec.",
      form_close: "Close",

      cart_title: "Your quote cart",
      cart_close: "Close cart",
      cart_empty: "You haven't added any rolls yet. Browse the catalog and add what you need.",
      cart_items_count: "items",
      cart_go_quote: "Request a quote for this order",
      cart_remove: "Remove",

      footer_tagline: "Precision thermal and bond paper for the point-of-sale ecosystem.",
      footer_nav_h: "Navigation",
      footer_company_h: "Company",
      footer_contact_h: "Contact",
      footer_rights: "All rights reserved.",
      footer_built: "Built with GSAP + CSS — no frameworks.",

      social_whatsapp: "Message us on WhatsApp",
      social_email: "Email us",
      social_tiktok: "Follow us on TikTok",
      social_youtube: "Subscribe on YouTube",
    },
  };
})();
